### PR TITLE
Support for Kubernetes 1.16, Closes #195

### LINKED ISSUE #195: Support for latest kubernetes version
**Description:**
I have a ready kubernetes cluster and I'm using kubernetes 1.16. Sadly I can't downgrade. More exactly I'm using these versions:
```
[root@k8s-master ~]# kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:09:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```
When I launch this command:
`helm install --dep-up --name wso2is-ingress /opt/wso2is_kubernetes/wso2_is_repo/kubernetes-is/advanced/is-pattern-1 --namespace kubernetes-iam-namespace`

I get this error:
```
[root@k8s-master ~]# helm install --dep-up --name wso2is-ingress /opt/wso2is_kubernetes/wso2_is_repo/kubernetes-is/advanced/is-pattern-1 --namespace kubernetes-iam-namespace
Error: validation failed: unable to recognize "": no matches for kind "Deployment" in version "extensions/v1beta1"
```
I tried to modify the file `${KUBERNETES_IS_HOME}/advanced/is-pattern-1/templates/identity-server-ingress.yaml` in this way:
```
#apiVersion: extensions/v1beta1
apiVersion: apps/v1
```
But I get this error:
```
[root@k8s-master ~]# helm install --dep-up --name wso2is-ingress /opt/wso2is_kubernetes/wso2_is_repo/kubernetes-is/advanced/is-pattern-1 --namespace kubernetes-iam-namespace
Error: validation failed: [unable to recognize "": no matches for kind "Deployment" in version "extensions/v1beta1", unable to recognize "": no matches for kind "Ingress" in version "apps/v1"]

```

Is there any way to solve this issue?

### PR DESCRIPTION
**Pull request by rgauss**
This ended up being a fairly easy fix.

- Updated NFS server provisioner and MySQL requirements

## Purpose
Closes #195

## Goals
Closing #195

## Approach
Update to newer requirements that support K8s 1.16

## User stories
#195

## Release note
Support for Kubernetes 1.16

## Documentation
N/A - no changes to deployment procedures

## Certification
N/A - does not affect certification

## Automation tests
N/A - Existing tests should be sufficient

## Related PRs
wso2/docker-is#202

### CODE REVIEW

**Comment by chirangaalwis** [comment]
@rgauss first of all thanks for the contribution.

We went through the PR $subject and description. Prior to merging can you please specify how this addresses the referenced issue https://github.com/wso2/kubernetes-is/issues/195?

As per my understanding this PR addresses two improvements.

- Upgrading the NFS Server Provisioner Helm chart version
- Upgrading the base MySQL Helm chart version

**Comment by rgauss** [comment]
@chirangaalwis, yes, that's correct.

**Comment by chirangaalwis** [comment]
@rgauss hence, I would adjust your PR $subject and description to address these improvements and remove the note on https://github.com/wso2/kubernetes-is/issues/195, as this issue is not addressed in this PR.

**Comment by rgauss** [comment]
@chirangaalwis, the changes in this PR (updating those requirements) are in fact what enable support on Kubernetes 1.16, so #195 is addressed by this PR.

I have, however, just realized that I made another change to the Docker image which will also be required.  I'll create a PR for that shortly and relate it here.

**Comment by rgauss** [comment]
I've updated the original comment to reference wso2/docker-is#202.

**Comment by chirangaalwis** [comment]
> I've updated the original comment to reference [wso2/docker-is#202](https://github.com/wso2/docker-is/pull/202).

@rgauss we will evaluate this and get back to you.

**Comment by chirangaalwis** [comment]
Closes https://github.com/wso2/kubernetes-is/issues/225.
Closes https://github.com/wso2/kubernetes-is/issues/226.

**Pull request merged**
